controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    use_sim_time: true

    diff_controller: # <- free name
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/src/diff_drive_controller.cpp
# https://github.com/joshnewans/mwe_diffdrive_bug/blob/main/controllers/dd_controller.yaml
diff_controller:
  ros__parameters:
    use_sim_time: true
    left_wheel_names: ['wheel_left_joint']
    right_wheel_names: ['wheel_right_joint']

    wheel_separation: 0.27
    wheels_per_side: 1
    wheel_radius: 0.0325
    wheel_separation_multiplier: 1.0
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 30
    update_rate: 30 

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    publish_rate: 30
    update_rate: 30  # Hz